defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"

compress_html:
  clippings: all
  comments: all
  startings: [head, body]

exclude:
  - Gemfile
  - Gemfile.lock
